DROP MATERIALIZED VIEW IF EXISTS atomicmarket_sale_mints CASCADE;
DROP MATERIALIZED VIEW IF EXISTS atomicmarket_buyoffer_mints CASCADE;
DROP MATERIALIZED VIEW IF EXISTS atomicmarket_auction_mints CASCADE;
